package org.epicgamer.kamikaze.summit.bean.codetable;
// default package
// Generated Sep 14, 2013 6:38:07 PM by Hibernate Tools 3.4.0.CR1

// Generated Sep 14, 2013 6:38:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CodeFieldType generated by hbm2java
 */
public class CodeFieldType implements java.io.Serializable
{

  private String  code;
  private String  description;
  private Integer sortOrder;
  private Set     fields = new HashSet(0);

  public CodeFieldType()
  {
  }

  public CodeFieldType(String code, String description)
  {
    this.code = code;
    this.description = description;
  }

  public CodeFieldType(String code, String description, Integer sortOrder,
      Set fields)
  {
    this.code = code;
    this.description = description;
    this.sortOrder = sortOrder;
    this.fields = fields;
  }

  public String getCode()
  {
    return this.code;
  }

  public void setCode(String code)
  {
    this.code = code;
  }

  public String getDescription()
  {
    return this.description;
  }

  public void setDescription(String description)
  {
    this.description = description;
  }

  public Integer getSortOrder()
  {
    return this.sortOrder;
  }

  public void setSortOrder(Integer sortOrder)
  {
    this.sortOrder = sortOrder;
  }

  public Set getFields()
  {
    return this.fields;
  }

  public void setFields(Set fields)
  {
    this.fields = fields;
  }

}
