package org.epicgamer.kamikaze.summit.bean.codetable;
// default package
// Generated Sep 14, 2013 6:38:07 PM by Hibernate Tools 3.4.0.CR1

// Generated Sep 14, 2013 6:38:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.beans.factory.annotation.Configurable;

/**
 * CodeProcessingSrcType generated by hbm2java
 */
@Configurable
@Entity
@Table(name = "CODE_PROCESSING_SRC_TYPE")
public class CodeProcessingSrcType implements java.io.Serializable
{

  /**
   * 
   */
  private static final long serialVersionUID = -5695742766052963020L;
  @Id
  @Column(name = "CODE")
  private String  code;
  @Column(name = "DESCRIPTION")
  private String  description;
  @Column(name = "SORT_ORDER")
  private Integer sortOrder;

  public CodeProcessingSrcType()
  {
  }

  public CodeProcessingSrcType(String code, String description)
  {
    this.code = code;
    this.description = description;
  }

  public CodeProcessingSrcType(String code, String description,
      Integer sortOrder)
  {
    this.code = code;
    this.description = description;
    this.sortOrder = sortOrder;
  }

  public String getCode()
  {
    return this.code;
  }

  public void setCode(String code)
  {
    this.code = code;
  }

  public String getDescription()
  {
    return this.description;
  }

  public void setDescription(String description)
  {
    this.description = description;
  }

  public Integer getSortOrder()
  {
    return this.sortOrder;
  }

  public void setSortOrder(Integer sortOrder)
  {
    this.sortOrder = sortOrder;
  }

}
