package org.epicgamer.kamikaze.summit.bean.codetable;
// default package
// Generated Sep 14, 2013 6:38:07 PM by Hibernate Tools 3.4.0.CR1

// Generated Sep 14, 2013 6:38:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CodeFieldSourceType generated by hbm2java
 */
public class CodeFieldSourceType implements java.io.Serializable
{

  private String  code;
  private String  description;
  private Integer sortOrder;
  private Set     fieldsForDefaultValueType = new HashSet(0);
  private Set     fieldsForSourceType       = new HashSet(0);

  public CodeFieldSourceType()
  {
  }

  public CodeFieldSourceType(String code, String description)
  {
    this.code = code;
    this.description = description;
  }

  public CodeFieldSourceType(String code, String description,
      Integer sortOrder, Set fieldsForDefaultValueType, Set fieldsForSourceType)
  {
    this.code = code;
    this.description = description;
    this.sortOrder = sortOrder;
    this.fieldsForDefaultValueType = fieldsForDefaultValueType;
    this.fieldsForSourceType = fieldsForSourceType;
  }

  public String getCode()
  {
    return this.code;
  }

  public void setCode(String code)
  {
    this.code = code;
  }

  public String getDescription()
  {
    return this.description;
  }

  public void setDescription(String description)
  {
    this.description = description;
  }

  public Integer getSortOrder()
  {
    return this.sortOrder;
  }

  public void setSortOrder(Integer sortOrder)
  {
    this.sortOrder = sortOrder;
  }

  public Set getFieldsForDefaultValueType()
  {
    return this.fieldsForDefaultValueType;
  }

  public void setFieldsForDefaultValueType(Set fieldsForDefaultValueType)
  {
    this.fieldsForDefaultValueType = fieldsForDefaultValueType;
  }

  public Set getFieldsForSourceType()
  {
    return this.fieldsForSourceType;
  }

  public void setFieldsForSourceType(Set fieldsForSourceType)
  {
    this.fieldsForSourceType = fieldsForSourceType;
  }

}
