// default package
// Generated Oct 31, 2013 9:11:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ApplicationPage generated by hbm2java
 */
@Entity
@Table(name = "application_page", schema = "public", uniqueConstraints = {
    @UniqueConstraint(columnNames = { "application_num", "page_num" }),
    @UniqueConstraint(columnNames = "application_num") })
public class ApplicationPage implements java.io.Serializable
{

  private int         id;
  private Page        page;
  private Application application;
  private int         applicationNum;
  private int         pageNum;

  public ApplicationPage()
  {
  }

  public ApplicationPage(int id, Page page, Application application,
      int applicationNum, int pageNum)
  {
    this.id = id;
    this.page = page;
    this.application = application;
    this.applicationNum = applicationNum;
    this.pageNum = pageNum;
  }

  @Id
  @Column(name = "id", unique = true, nullable = false)
  public int getId()
  {
    return this.id;
  }

  public void setId(int id)
  {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "page_id", nullable = false)
  public Page getPage()
  {
    return this.page;
  }

  public void setPage(Page page)
  {
    this.page = page;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "application_id", nullable = false)
  public Application getApplication()
  {
    return this.application;
  }

  public void setApplication(Application application)
  {
    this.application = application;
  }

  @Column(name = "application_num", unique = true, nullable = false)
  public int getApplicationNum()
  {
    return this.applicationNum;
  }

  public void setApplicationNum(int applicationNum)
  {
    this.applicationNum = applicationNum;
  }

  @Column(name = "page_num", nullable = false)
  public int getPageNum()
  {
    return this.pageNum;
  }

  public void setPageNum(int pageNum)
  {
    this.pageNum = pageNum;
  }

}
