// default package
// Generated Oct 31, 2013 9:11:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", schema = "public")
public class Region implements java.io.Serializable
{

  private int                id;
  private CodeRegionPosition codeRegionPosition;
  private CodeRegionType     codeRegionType;
  private String             name;
  private Set<PageRegion>    pageRegions  = new HashSet<PageRegion>(0);
  private Set<RegionField>   regionFields = new HashSet<RegionField>(0);

  public Region()
  {
  }

  public Region(int id, String name)
  {
    this.id = id;
    this.name = name;
  }

  public Region(int id, CodeRegionPosition codeRegionPosition,
      CodeRegionType codeRegionType, String name, Set<PageRegion> pageRegions,
      Set<RegionField> regionFields)
  {
    this.id = id;
    this.codeRegionPosition = codeRegionPosition;
    this.codeRegionType = codeRegionType;
    this.name = name;
    this.pageRegions = pageRegions;
    this.regionFields = regionFields;
  }

  @Id
  @Column(name = "id", unique = true, nullable = false)
  public int getId()
  {
    return this.id;
  }

  public void setId(int id)
  {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "region_position")
  public CodeRegionPosition getCodeRegionPosition()
  {
    return this.codeRegionPosition;
  }

  public void setCodeRegionPosition(CodeRegionPosition codeRegionPosition)
  {
    this.codeRegionPosition = codeRegionPosition;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "region_type")
  public CodeRegionType getCodeRegionType()
  {
    return this.codeRegionType;
  }

  public void setCodeRegionType(CodeRegionType codeRegionType)
  {
    this.codeRegionType = codeRegionType;
  }

  @Column(name = "name", nullable = false, length = 1000)
  public String getName()
  {
    return this.name;
  }

  public void setName(String name)
  {
    this.name = name;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
  public Set<PageRegion> getPageRegions()
  {
    return this.pageRegions;
  }

  public void setPageRegions(Set<PageRegion> pageRegions)
  {
    this.pageRegions = pageRegions;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
  public Set<RegionField> getRegionFields()
  {
    return this.regionFields;
  }

  public void setRegionFields(Set<RegionField> regionFields)
  {
    this.regionFields = regionFields;
  }

}
