package org.awiki.kamikaze.summit.domain.codetable;
// Generated Oct 31, 2013 9:11:16 PM by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * CodeFieldType generated by hbm2java
 */
@Entity
@Table(name = "CODE_LABEL_TYPE")
public class CodeLabelType implements java.io.Serializable, CodeTable
{
  public static final String IS_LEFT_PREFIX  = "LEFT_";
  public static final String IS_RIGHT_PREFIX = "RIGHT_";

  public static final String PARTIAL_OPTIONAL_CODE = "_OPT";
  public static final String PARTIAL_MANDATORY_CODE  = "_MAND";

  /**
   * 
   */
  private static final long serialVersionUID = 48595818217207L;
  
  private String     code;
  private String     description;
  private Long       sortOrder;

  public CodeLabelType()
  {
  }

  public CodeLabelType(String code, String description)
  {
    this.code = code;
    this.description = description;
  }

  public CodeLabelType(String code, String description, Long sortOrder
      /*,Set<Field> fields*/)
  {
    this.code = code;
    this.description = description;
    this.sortOrder = sortOrder;
    //this.fields = fields;
  }

  @Id
  @Column(name = "code", unique = true, nullable = false, length = 10)
  public String getCode()
  {
    return this.code;
  }

  public void setCode(String code)
  {
    this.code = code;
  }

  @Column(name = "description", nullable = false)
  public String getDescription()
  {
    return this.description;
  }

  public void setDescription(String description)
  {
    this.description = description;
  }

  @Column(name = "sort_order")
  public Long getSortOrder()
  {
    return this.sortOrder;
  }

  public void setSortOrder(Long sortOrder)
  {
    this.sortOrder = sortOrder;
  }
}
