package org.awiki.kamikaze.summit.domain;
// Generated Oct 31, 2013 9:11:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Application generated by hbm2java
 */
@Entity
@Table(name = "application", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "application_num"))
public class Application implements java.io.Serializable
{

  /**
   * 
   */
  private static final long serialVersionUID = -4781215033779957877L;
  
  private long                     id;
  private long                     applicationNum;
  private String                  name;
  private Set<ApplicationPage>    applicationPages     = new HashSet<ApplicationPage>(
                                                           0);
  private Set<ApplicationSchemas> applicationSchemases = new HashSet<ApplicationSchemas>(
                                                           0);

  public Application()
  {
  }

  public Application(long id, long applicationNum, String name)
  {
    this.id = id;
    this.applicationNum = applicationNum;
    this.name = name;
  }

  public Application(long id, long applicationNum, String name,
      Set<ApplicationPage> applicationPages,
      Set<ApplicationSchemas> applicationSchemases)
  {
    this.id = id;
    this.applicationNum = applicationNum;
    this.name = name;
    this.applicationPages = applicationPages;
    this.applicationSchemases = applicationSchemases;
  }

  @Id
  @Column(name = "id", unique = true, nullable = false)
  public long getId()
  {
    return this.id;
  }

  public void setId(long id)
  {
    this.id = id;
  }

  @Column(name = "application_num", unique = true, nullable = false)
  public long getApplicationNum()
  {
    return this.applicationNum;
  }

  public void setApplicationNum(long applicationNum)
  {
    this.applicationNum = applicationNum;
  }

  @Column(name = "name", nullable = false, length = 1000)
  public String getName()
  {
    return this.name;
  }

  public void setName(String name)
  {
    this.name = name;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "application")
  public Set<ApplicationPage> getApplicationPages()
  {
    return this.applicationPages;
  }

  public void setApplicationPages(Set<ApplicationPage> applicationPages)
  {
    this.applicationPages = applicationPages;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "application")
  public Set<ApplicationSchemas> getApplicationSchemases()
  {
    return this.applicationSchemases;
  }

  public void setApplicationSchemases(
      Set<ApplicationSchemas> applicationSchemases)
  {
    this.applicationSchemases = applicationSchemases;
  }

}
