package org.awiki.kamikaze.summit.domain;
// Generated Oct 31, 2013 9:11:16 PM by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * ApplicationPage generated by hbm2java
 */
@Entity
@Table(name = "APPLICATION_PAGE", uniqueConstraints = {
    @UniqueConstraint(columnNames = { "APPLICATION_ID", "PAGE_NUM" }),
    @UniqueConstraint(columnNames = "APPLICATION_ID") })
public class ApplicationPage implements java.io.Serializable
{

  /**
   * 
   */
  private static final long serialVersionUID = 4306085506056915445L;
  
  private long         id;
  private Page        page;
  private Application application;
  private long         pageNum;

  public ApplicationPage()
  {
  }

  public ApplicationPage(long id, Page page, Application application,
      long pageNum)
  {
    this.id = id;
    this.page = page;
    this.application = application;
    this.pageNum = pageNum;
  }

  @Id
  @Column(name = "ID", unique = true, nullable = false)
  public long getId()
  {
    return this.id;
  }

  public void setId(long id)
  {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "PAGE_ID", nullable = false)
  public Page getPage()
  {
    return this.page;
  }

  public void setPage(Page page)
  {
    this.page = page;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "APPLICATION_ID", nullable = false)
  public Application getApplication()
  {
    return this.application;
  }

  public void setApplication(Application application)
  {
    this.application = application;
  }

  @Column(name = "PAGE_NUM", nullable = false)
  public long getPageNum()
  {
    return this.pageNum;
  }

  public void setPageNum(long pageNum)
  {
    this.pageNum = pageNum;
  }

}
