package org.awiki.kamikaze.summit.domain;
// Generated Oct 31, 2013 9:11:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ApplicationSchemasId generated by hbm2java
 */
@Embeddable
public class ApplicationSchemasId implements java.io.Serializable
{

  /**
   * 
   */
  private static final long serialVersionUID = 1030444283435841329L;
  
  private int    applicationId;
  private String schemaName;

  public ApplicationSchemasId()
  {
  }

  public ApplicationSchemasId(int applicationId, String schemaName)
  {
    this.applicationId = applicationId;
    this.schemaName = schemaName;
  }

  @Column(name = "application_id", nullable = false)
  public int getApplicationId()
  {
    return this.applicationId;
  }

  public void setApplicationId(int applicationId)
  {
    this.applicationId = applicationId;
  }

  @Column(name = "schema_name", nullable = false, length = 100)
  public String getSchemaName()
  {
    return this.schemaName;
  }

  public void setSchemaName(String schemaName)
  {
    this.schemaName = schemaName;
  }

  public boolean equals(Object other)
  {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof ApplicationSchemasId))
      return false;
    ApplicationSchemasId castOther = (ApplicationSchemasId) other;

    return (this.getApplicationId() == castOther.getApplicationId())
        && ((this.getSchemaName() == castOther.getSchemaName()) || (this
            .getSchemaName() != null && castOther.getSchemaName() != null && this
            .getSchemaName().equals(castOther.getSchemaName())));
  }

  public int hashCode()
  {
    int result = 17;

    result = 37 * result + this.getApplicationId();
    result = 37 * result
        + (getSchemaName() == null ? 0 : this.getSchemaName().hashCode());
    return result;
  }

}
