package org.awiki.kamikaze.summit.domain;
// Generated Oct 31, 2013 9:11:16 PM by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import org.awiki.kamikaze.summit.domain.codetable.CodeSourceType;

/**
 * PageProcessing generated by hbm2java
 */
@Entity
@Table(name = "PAGE_PROCESSING_SOURCE_SELECT")
public class PageProcessingSourceSelect implements java.io.Serializable
{

  /**
   * This domain contains a list of fields that we wish to select values into.
   * It is associated with a pageProcessingSource of type 'dml_selrow'
   * Values selected within the corresponding 'select' clause associated with the PageProcessingSource.Source are populated by fieldIndex order
   *   and then when region processing occurs, if a field name matches one specified here, values are auto-filled.
   */
  private static final long serialVersionUID = -4302933211895462441L;
  
  private long                   id;
  private PageProcessingSource   pageProcessingSource;
  private long                   fieldIndex;
  private String                 fieldName;

  public PageProcessingSourceSelect()
  {
  }

  @Id
  @Column(name = "ID", unique = true, nullable = false)
  public long getId()
  {
    return this.id;
  }

  public void setId(long id)
  {
    this.id = id;
  }
  
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "PAGE_PROCESSING_SOURCE_ID", nullable = false)
  public PageProcessingSource getPageProcessingSource()
  {
    return this.pageProcessingSource;
  }

  public void setPageProcessingSource(PageProcessingSource pageProcessingSource)
  {
    this.pageProcessingSource = pageProcessingSource;
  }

  @Column(name = "FIELD_INDEX", nullable = false)
  public long getFieldIndex()
  {
    return this.fieldIndex;
  }

  public void setFieldIndex(Long fieldIndex)
  {
    this.fieldIndex = fieldIndex;
  }

  @Column(name = "FIELD_NAME", nullable = false)
  public String getFieldName()
  {
    return this.fieldName;
  }

  public void setFieldName(String fieldName)
  {
    this.fieldName = fieldName;
  }
}
