package org.awiki.kamikaze.summit.domain;
// Generated Oct 31, 2013 9:11:16 PM by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * PageRegion generated by hbm2java
 */
@Entity
@Table(name = "PAGE_REGION", uniqueConstraints = {
    @UniqueConstraint(columnNames = { "PAGE_ID", "REGION_ID" }),
    @UniqueConstraint(columnNames = { "PAGE_ID", "REGION_NUM" }) })
public class PageRegion implements java.io.Serializable
{

  /**
   * 
   */
  private static final long serialVersionUID = 7071227548283247644L;
  
  private long    id;
  private Page   page;
  private Region region;
  private long    regionNum;

  public PageRegion()
  {
  }

  public PageRegion(long id, Page page, Region region, long regionNum)
  {
    this.id = id;
    this.page = page;
    this.region = region;
    this.regionNum = regionNum;
  }

  @Id
  @Column(name = "id", unique = true, nullable = false)
  public long getId()
  {
    return this.id;
  }

  public void setId(long id)
  {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "page_id", nullable = false)
  public Page getPage()
  {
    return this.page;
  }

  public void setPage(Page page)
  {
    this.page = page;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "region_id", nullable = false)
  public Region getRegion()
  {
    return this.region;
  }

  public void setRegion(Region region)
  {
    this.region = region;
  }

  @Column(name = "region_num", nullable = false)
  public long getRegionNum()
  {
    return this.regionNum;
  }

  public void setRegionNum(long regionNum)
  {
    this.regionNum = regionNum;
  }

}
