package org.awiki.kamikaze.summit.domain;
// Generated Oct 31, 2013 9:11:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.awiki.kamikaze.summit.domain.codetable.CodeProcessingSrcType;
import org.awiki.kamikaze.summit.domain.codetable.CodeProcessingType;

/**
 * PageProcessing generated by hbm2java
 */
@Entity
@Table(name = "page_processing", schema = "public")
public class PageProcessing implements java.io.Serializable
{

  /**
   * This domain stores the request processing details of a particular summit page.
   * E.g. you could have page processing function written in SQL that inserts values
   * into a database table.
   */
  private static final long serialVersionUID = -4307936142895462501L;
  
  private int                   id;
  private CodeProcessingSrcType codeProcessingSrcType; // e.g. SQL, pg/sql
  private Page                  page;
  private CodeProcessingType    codeProcessingType;    // e.g. clear session state, DML, redirect to another page
  private int                   processingNum;         // in which order this processing occurs.
  private String                source;

  public PageProcessing()
  {
  }

  public PageProcessing(int id, CodeProcessingSrcType codeProcessingSrcType,
      Page page, CodeProcessingType codeProcessingType, int processingNum)
  {
    this.id = id;
    this.codeProcessingSrcType = codeProcessingSrcType;
    this.page = page;
    this.codeProcessingType = codeProcessingType;
    this.processingNum = processingNum;
  }

  public PageProcessing(int id, CodeProcessingSrcType codeProcessingSrcType,
      Page page, CodeProcessingType codeProcessingType, int processingNum,
      String source)
  {
    this.id = id;
    this.codeProcessingSrcType = codeProcessingSrcType;
    this.page = page;
    this.codeProcessingType = codeProcessingType;
    this.processingNum = processingNum;
    this.source = source;
  }

  @Id
  @Column(name = "id", unique = true, nullable = false)
  public int getId()
  {
    return this.id;
  }

  public void setId(int id)
  {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "source_type", nullable = false)
  public CodeProcessingSrcType getCodeProcessingSrcType()
  {
    return this.codeProcessingSrcType;
  }

  public void setCodeProcessingSrcType(
      CodeProcessingSrcType codeProcessingSrcType)
  {
    this.codeProcessingSrcType = codeProcessingSrcType;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "page_id", nullable = false)
  public Page getPage()
  {
    return this.page;
  }

  public void setPage(Page page)
  {
    this.page = page;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "type", nullable = false)
  public CodeProcessingType getCodeProcessingType()
  {
    return this.codeProcessingType;
  }

  public void setCodeProcessingType(CodeProcessingType codeProcessingType)
  {
    this.codeProcessingType = codeProcessingType;
  }

  @Column(name = "processing_num", nullable = false)
  public int getProcessingNum()
  {
    return this.processingNum;
  }

  public void setProcessingNum(int processingNum)
  {
    this.processingNum = processingNum;
  }

  @Column(name = "source", length = 10000)
  public String getSource()
  {
    return this.source;
  }

  public void setSource(String source)
  {
    this.source = source;
  }

}
