package org.awiki.kamikaze.summit.domain;
// Generated Oct 31, 2013 9:11:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RegionField generated by hbm2java
 */
@Entity
@Table(name = "region_field", schema = "public")
public class RegionField implements java.io.Serializable
{

  private long    id;
  private Field  field;
  private Region region;
  private long    fieldNum;

  public RegionField()
  {
  }

  public RegionField(long id, Field field, Region region, long fieldNum)
  {
    this.id = id;
    this.field = field;
    this.region = region;
    this.fieldNum = fieldNum;
  }

  @Id
  @Column(name = "id", unique = true, nullable = false)
  public long getId()
  {
    return this.id;
  }

  public void setId(long id)
  {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "field_id", nullable = false)
  public Field getField()
  {
    return this.field;
  }

  public void setField(Field field)
  {
    this.field = field;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "region_id", nullable = false)
  public Region getRegion()
  {
    return this.region;
  }

  public void setRegion(Region region)
  {
    this.region = region;
  }

  @Column(name = "field_num", nullable = false)
  public long getFieldNum()
  {
    return this.fieldNum;
  }

  public void setFieldNum(long fieldNum)
  {
    this.fieldNum = fieldNum;
  }

}
