package org.awiki.kamikaze.summit.domain;
// Generated Oct 31, 2013 9:11:16 PM by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Field generated by hbm2java
 */
@Entity
@Table(name = "SOURCE_METADATA_COLS")
public class SourceMetadataCols implements java.io.Serializable
{
  private static final long serialVersionUID = -79999513396L;
  
  private long                      id;
  private SourceMetadata            sourceMetadata;
  private long                      columnOrder;
  private String                    columnName;
  private long                      columnType;
  
  public SourceMetadataCols()
  {
  }

  @Id
  @Column(name = "ID", unique = true, nullable = false)
  public long getId()
  {
    return this.id;
  }

  public void setId(long id)
  {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "SOURCE_METADATA_ID")
  public SourceMetadata getSourceMetadata()
  {
    return this.sourceMetadata;
  }

  public void setSourceMetadata(SourceMetadata sourceMetadata)
  {
    this.sourceMetadata = sourceMetadata;
  }

  @Column(name = "COLUMN_ORDER", nullable = false)
  public long getColumnOrder()
  {
    return columnOrder;
  }

  public void setColumnOrder(long columnOrder)
  {
    this.columnOrder = columnOrder;
  }

  @Column(name = "COLUMN_NAME", length = 200, nullable = false)
  public String getColumnName()
  {
    return columnName;
  }

  public void setColumnName(String columnName)
  {
    this.columnName = columnName;
  }

  @Column(name = "COLUMN_TYPE", nullable = false)
  public long getColumnType()
  {
    return columnType;
  }

  public void setColumnType(long columnType)
  {
    this.columnType = columnType;
  }
}
