package org.awiki.kamikaze.summit.domain;
// Generated Oct 31, 2013 9:11:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Field generated by hbm2java
 */
@Entity
@Table(name = "SOURCE_METADATA")
public class SourceMetadata implements java.io.Serializable
{
  private static final long serialVersionUID = -34196693513396L;
  
  private long                      id;
  private Source                    source;
  private List<SourceMetadataCols>  sourceMetadataCols = new ArrayList<>();
  private Date                      dateCreated;
  private Date                      lastUpdated;
  private String                    updatedBy;
  
  public SourceMetadata()
  {
  }

  @Id
  @Column(name = "ID", unique = true, nullable = false)
  public long getId()
  {
    return this.id;
  }

  public void setId(long id)
  {
    this.id = id;
  }

  @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
  @JoinColumn(name = "SOURCE_ID")
  public Source getSource()
  {
    return source;
  }

  public void setSource(Source source)
  {
    this.source = source;
  }

  @OneToMany(fetch = FetchType.EAGER, mappedBy="sourceMetadata")
  @OrderBy("columnOrder asc")
  public List<SourceMetadataCols> getSourceMetadataCols()
  {
    return sourceMetadataCols;
  }

  public void setSourceMetadataCols(List<SourceMetadataCols> sourceMetadataCols)
  {
    this.sourceMetadataCols = sourceMetadataCols;
  }

  @Generated(GenerationTime.INSERT)
  @Column(name = "DATE_CREATED", nullable = true)
  @Temporal(TemporalType.DATE)
  public Date getDateCreated()
  {
    return dateCreated;
  }

  public void setDateCreated(Date dateCreated)
  {
    this.dateCreated = dateCreated;
  }

  @Column(name = "LAST_UPDATED", nullable = true)
  @Temporal(TemporalType.DATE)
  public Date getLastUpdated()
  {
    return lastUpdated;
  }

  public void setLastUpdated(Date lastUpdated)
  {
    this.lastUpdated = lastUpdated;
  }

  @Column(name = "UPDATED_BY", length = 200, nullable = true)
  public String getUpdatedBy()
  {
    return updatedBy;
  }

  public void setUpdatedBy(String updatedBy)
  {
    this.updatedBy = updatedBy;
  }

}
